version: '3'
services:
  dashboard:
    build:
      context: https://github.com/AndsoiIo/betagr-dashboard.git#dev
      dockerfile: server/Dockerfile
    ports:
      - 5000:5000
    command: python server/app.py
    depends_on:
      - liquibase
    env_file:
      .env

  sso:
    build:
      context: https://github.com/tukva/sanic-docker.git#dev
      dockerfile: server/Dockerfile
    ports:
      - 8080:8080
    command: python server/app.py
    depends_on:
      - liquibase
    env_file:
      .env

  aggregator:
    build:
      context: https://github.com/tukva/aggregator.git#dev
      dockerfile: server/Dockerfile
    ports:
      - 3000:3000
    command: python server/app.py
    depends_on:
      - liquibase
    env_file:
      .env

  parser:
    build: 
      context: https://github.com/tukva/parser.git#dev
      dockerfile: server/Dockerfile
    ports:
      - 8000:8000
    command: python server/app.py
    depends_on:
      - liquibase
    env_file:
      .env

  liquibase:
        image: "webdevops/liquibase:postgres"
        volumes:
            - .:/liquibase
        command: update
        environment:
            - LIQUIBASE_CHANGELOG=${LIQUIBASE_CHANGELOG}
            - LIQUIBASE_URL=jdbc:postgresql://host.docker.internal:${POSTGRES_PORT}/${POSTGRES_DB}
            - LIQUIBASE_USERNAME=${POSTGRES_USER}
            - LIQUIBASE_PASSWORD=${POSTGRES_PASSWORD}
